### ISSUE TITLE
Create workflow button is not working on Internet Explorer 11

### ISSUE THREAD

**Issue by fviale** [ow2-proactive/studio#328]
On IE11, when clicking on the create workflow button, the following javascript message appears:

Line: 89
Error : The object does not handle the property or method « startsWith »

The issue occurs on line 89 of WorkflowListView.js:

if (modelName.startsWith("Untitled " + this.mode + " "))

**Comment by fviale** [comment]
This discussion seems related to the problem:
https://forums.asp.net/t/1847109.aspx?startsWith+not+works+in+javascript+for+me+

**Comment by lpellegr** [comment]
https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith#Polyfill

**Comment by fviale** [comment]
Thanks laurent, do you think the prototype method should be added somewhere instead of replacing startsWith with indexOf ?

**Comment by lpellegr** [comment]
Yes, this would prevent the same problem from happening again if `startsWith` is used inadvertently again.

**Comment by paraita** [comment]
I found some javascript libraries that might contain the missing functions for IE:

- [polyfiller](https://github.com/Polyfiller/polyfiller)
- [es5-shim](https://github.com/es-shims/es5-shim)

There are multiple problems with those libraries:

- polyfiller is not maintained anymore
- es5-shim makes all javascript fail silently (by design)
- You actually have to declare the functions you need to polyfill (as loading all would have a huge impact on memory) with es5-shim.

There is also Modernizr that is currently used by some of our dependencies, it also relies on the per-feature trigger system like es5-shim. I'd prefer to go with this solution but it will require a lot of time to check what feature we'd need to enable and it might also conflict with the version needed by our dependencies.

**Comment by paraita** [comment]
or I can just manually polyfill the missing polyfill methods we need

**Comment by fviale** [comment]
Too bad for polyfiller, it looked quite nice. I did not find the reason why
it was marked in the title as "obsolete".

**Comment by paraita** [comment]
because it hasn't been updated in a year and 3 of its dependencies are also out-of-date, it's going to be a pain to maintain. Do you think it is worth trying it ? It should take an hour and half to change our code and do some testing.
