### ISSUE TITLE
When opening the workflow catalog window, only the first 20 workflows of a bucket are displayed in the list

### ISSUE THREAD

**Issue by laurianed** [ow2-proactive/studio#338]
If the catalog is open, only the first 20 workflows of a selected workflow appear in the list. If new workflows are added, they are displayed. But once the catalog is closed and open again, they don't appear anymore.

**Comment by fviale** [comment]
This is due to the fact that pagination is not yet implemented in the catalog, so it is considered as an improvement.

**Comment by lpellegr** [comment]
Please note that pagination is implemented in the Workflow Catalog but not used in the Studio.

**Comment by ShatalovYaroslav** [comment]
Actually the issue is not relevant any more as we don't have any more the pagination in new catalog.
Also in studio we show all existing buckets, workflows and revisions with scroll bar.
![studio_catalog](https://user-images.githubusercontent.com/17726918/33667649-b86305b4-da9d-11e7-891f-5b764aae75d2.PNG)

**Comment by fviale** [comment]
fixed
